# Generated by Django 2.2.7 on 2019-12-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=25)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studantname', models.CharField(max_length=25)),
                ('c_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libra.Studant')),
                ('custname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libra.Books')),
            ],
        ),
    ]
