# Generated by Django 2.2.7 on 2019-12-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow1',
            name='bookname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libra.Books'),
        ),
        migrations.AlterField(
            model_name='borrow1',
            name='custname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libra.Studant'),
        ),
    ]
