# Generated by Django 2.2.7 on 2019-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0002_auto_20191207_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
